FROM hyperledger/fabric-peer:2.5

RUN rm -rf /etc/hyperledger/fabric/msp /etc/hyperledger/fabric/tls
COPY organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp /etc/hyperledger/fabric/msp
COPY organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls /etc/hyperledger/fabric/tls
RUN mkdir -p /etc/hyperledger/fabric/msp/admincerts
COPY organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem /etc/hyperledger/fabric/msp/admincerts/
COPY core.yaml /etc/hyperledger/fabric/core.yaml
